// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTu9nkE2OIv0yEjOitBTfE2w5rcBj_9wc',
    appId: '1:366412843128:web:dfd6cc2b6c544ab009458d',
    messagingSenderId: '366412843128',
    projectId: 'habitvibe-2k25',
    authDomain: 'habitvibe-2k25.firebaseapp.com',
    storageBucket: 'habitvibe-2k25.firebasestorage.app',
    measurementId: 'G-5YF0PDZ9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ChljJ4_RCqBjAMVbdDiG5E8TeXBfSWk',
    appId: '1:366412843128:android:170482ab0c351a0d09458d',
    messagingSenderId: '366412843128',
    projectId: 'habitvibe-2k25',
    storageBucket: 'habitvibe-2k25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOs6-151SpH09ZIq9wBSCp_RJaJcePso',
    appId: '1:366412843128:ios:9013b87198bcc6b009458d',
    messagingSenderId: '366412843128',
    projectId: 'habitvibe-2k25',
    storageBucket: 'habitvibe-2k25.firebasestorage.app',
    iosBundleId: 'com.example.habitoriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOs6-151SpH09ZIq9wBSCp_RJaJcePso',
    appId: '1:366412843128:ios:9013b87198bcc6b009458d',
    messagingSenderId: '366412843128',
    projectId: 'habitvibe-2k25',
    storageBucket: 'habitvibe-2k25.firebasestorage.app',
    iosBundleId: 'com.example.habitoriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTu9nkE2OIv0yEjOitBTfE2w5rcBj_9wc',
    appId: '1:366412843128:web:d4e01eaa566ab36d09458d',
    messagingSenderId: '366412843128',
    projectId: 'habitvibe-2k25',
    authDomain: 'habitvibe-2k25.firebaseapp.com',
    storageBucket: 'habitvibe-2k25.firebasestorage.app',
    measurementId: 'G-W2D9PNHWEL',
  );
}
